name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # 只有打 tag 时才发布

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore R.DescriptionModelGenerator/R.DescriptionModelGenerator.csproj

      - name: Build
        run: dotnet build R.DescriptionModelGenerator/R.DescriptionModelGenerator.csproj --configuration Release --no-restore

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack R.DescriptionModelGenerator/R.DescriptionModelGenerator.csproj --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
